### ISSUE TITLE
Make changes to RegisterActivity and create transition from Register to LoginActivity

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#10]
You have to create a new empty activity named as "LoginActivity" along with its layout file in the same location as all the other activities. Also, you have to create a transition in the RegisterActivity to the LoginActivity.  Change the "Already Have an Account? Login" String to just Already Have an Account, add a seperate TextView for "Login" and add an onClickListener to the Login TextView. on Clicking the Login TextView, there should be a transition from the RegisterActivity to LoginActivity.
Also hide the status bar from the top of the screen. 

![image](https://user-images.githubusercontent.com/97402494/208300157-24773b03-7648-4253-a027-eede65d5c62d.png)

You have to write the code [here](https://github.com/opencodeiiita/SuperQuizzer/blob/main/app/src/main/java/com/example/superquizzer/RegisterActivity.kt)
---
In case you have any further doubts, feel free to ask in the SuperQuizzer discord channel.

**Comment by unreasonable2003** [comment]
Claim

**Comment by anshgeez31** [comment]
claim

**Comment by RibhavBansal** [comment]
claim
