### ISSUE TITLE
ResultActivity layout

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#100]
Create a layout for result activity of the application, clicking the next button when 10th question is answered should go to this Activity, it should display the final score and contain a button to go back to the home screen and a button to share the application with others. It should also contain text saying Congratulations + username of the current user.  use colorful background gradient according to the theme of the application. You need to do both layout and coding part. If you have any other doubts feel free to ask on the discord server.

**Comment by zitsav** [comment]
claim 😔
