### ISSUE TITLE
Navigation Header

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#102]
Add a Navigation Header to the Navigation View, it should contain an ImageView of any default Avatar and display the email address of the currently signed in user. 

This  issue  requires **Firebase Implementation** in our application. Provide your email address  by commenting while claiming the issue or after claiming the issue, and I will add you as a member to the Project's Firebase Portal
You can access it then here: https://console.firebase.google.com/u/3/project/superquizzer-8cb6c/overview 

Here is an example for your reference: 
![image](https://user-images.githubusercontent.com/97402494/211272410-9e4b0ee6-cc67-44fb-a3ed-46a0d35ca4e8.png)

To get email of current signed in user , refer to the documentation: https://firebase.google.com/docs/auth/users
Attach screenshot when submitting a PR.

**Comment by Koshal7** [comment]
claim

**Comment by IEC2021103Abhinav** [comment]
claim
