### ISSUE TITLE
Finishing Up

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#106]
The questions for all the other activities have already been set, so make new activities for all the different Categories and implement their functioning as well, and they should all display a ResultActivity at the end with their scores similar to the ScienceActivity right now.
If you have any doubts you can ask on discord.

**Comment by zitsav** [comment]
claim

**Comment by IEC2021103Abhinav** [comment]
Claim

**Comment by Koshal7** [comment]
claim 🫠
