### ISSUE TITLE
SettingsActivity

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#107]
This  issue  requires **Firebase Implementation** in our application. Provide your email address  by commenting while claiming the issue or after claiming the issue, and I will add you as a member to the Project's Firebase Portal
You can access it then here: https://console.firebase.google.com/u/3/project/superquizzer-8cb6c/overview 

Clicking on the Settings option in the Navigation drawer should take you to a new activity named SettingsActivity. It should have the options to Enable/Disable Dark Mode and delete a user's account.
If user wants to delete their account a DialogBox should appear asking them if they are sure they want to delete their account or not, if Yes is clicked, the app should close and the user's account must be deleted from the database.

For account deletion reference: https://firebase.google.com/docs/auth/users
For dark mode reference: https://youtu.be/BoGpEiz0MI8

**Comment by Koshal7** [comment]
claim

**Comment by IEC2021103Abhinav** [comment]
Claim
