### ISSUE TITLE
Sound Effects

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#111]
Search for a sound effect for correct answer and incorrect answer and import them into the project. Now, you have to make it so that in any of the question activities if a option is answered correctly, then the correct answer sound effect should play, else the incorrect option sound effect should play. Make sure the sound effects are no more than 2s long as repetitive long durations of sound can be annoying.

**Comment by zitsav** [comment]
claim

**Comment by IEC2021103Abhinav** [comment]
Claim
