### ISSUE TITLE
Animate Transition to ResultActivity.

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#118]
In each quiz category, whenever finish is pressed after the 10th question, the transition to ResultActivity needs to animated to something like this: 
![1_27XsdPAmg_2GEEjvRO47kg](https://user-images.githubusercontent.com/97402494/211929730-8668a496-b339-488a-a533-39af72f3a082.gif)

Refer to this article for your reference: https://medium.com/mobile-app-development-publication/animate-android-activities-transition-bf7f89a74b35

Attach a .gif of going to the resultactivity from any of the question activities when submitting a PR.

**Comment by IEC2021103Abhinav** [comment]
Claim
