### ISSUE TITLE
Mute MediaPlayer

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#119]
In the SettingsActivity, add an option to mute the media player if the user wants to. The quiz activity's should not play any sound if this setting is enabled.  Use vectors similar to these for the Mute button option:

![image](https://user-images.githubusercontent.com/97402494/211989531-e7e6eb28-eaa3-46a2-8a10-7667863817c7.png)
![image](https://user-images.githubusercontent.com/97402494/211989553-eb1b14a7-d237-4247-bcc1-324e17bbd0b0.png)

**Comment by zitsav** [comment]
claim

**Comment by akshatsgh** [comment]
Claim
