### ISSUE TITLE
Animatoo Library

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#120]
For all the other tranisitions, we will be using Animatoo Library to implement them.
Check out the Library here: https://github.com/AtifSayings/Animatoo
You have to import this library in our project and do the following tasks:
1. On clicking on any quiz activity from the MainActivity, shrink animation must be shown for the transition.
2. On pressing back button in any activity, slide Left animation should be used.
3. Spin animation should be displayed when the user presses the Login Button and login is successful (Transition to MainActivity)
Show a .gif of any one of the transitions working while submitting a PR.

**Comment by akshatsgh** [comment]
Claim
