### ISSUE TITLE
Write logic for registerUser() function in the RegisterActivity

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#18]
You have to create a new function in  [RegisterActivity.kt](https://github.com/opencodeiiita/SuperQuizzer/blob/main/app/src/main/java/com/example/superquizzer/RegisterActivity.kt) named resgisterUser() , this function should check that if first name, last name, email address, password, confirm password any of the EditText's are blank it should return a toast saying that "First Name cannot be blank" "Last name cannot be blank" etc.  Also, if the checkbox is not checked it should return a toast saying Terms and Conditions are not checked, and lastly if the password and confirm password fields do not match it should return a toast saying "Password and confirm password do not match". In case everything is correct , it should return a toast saying "Registration successful". 
Also add an onClickListener to the Register button which should call the registerUser() function, 

![image](https://user-images.githubusercontent.com/97402494/208403624-7eab6410-805a-4aef-a976-3971c2279140.png)

**Comment by zitsav** [comment]
claim

**Comment by IEC2021103Abhinav** [comment]
Claim

**Comment by RibhavBansal** [comment]
claim

**Comment by IEC2021103Abhinav** [comment]
Claim

**Comment by SuhailAhmadKhan** [comment]
@IEC2021103Abhinav  you have been assigned this issue, you have 48 hours to work on it.

**Comment by SuhailAhmadKhan** [comment]
@IEC2021103Abhinav  updates? also try to sync the current changes to your forked repo and then pull the changes that have happened. There has been some new code added in the RegisterActivity. you can copy paste the code you had written in the old version to the new version.
