### ISSUE TITLE
Design the SplashScreen in XML and replace the icon of the application.

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#25]
You have to set the SplashScreen of the application as the figma design attached below, simply extract the PNG for the figma file from the link below and set an ImageView in the SplashActivity's layout file with proper constraints, it should fill X and Y completely (wrap content properly) and work for different screen resolutions.

 __Attach a .gif of opening the application when submitting a pull request.__

https://www.figma.com/file/MQWX5XXxj6nbQE7tVNg9MV/Untitled?node-id=0%3A1&t=EpAGjwF2ResVrIIN-1

also, replace the icon of the app with the icon attached in the figma file below: 

https://www.figma.com/file/G5HaxbczBCvCzdfNRjKOTc/Super-Quizzer-logo?node-id=0%3A1&t=d0MTczcyuYoB0tTB-1

**Comment by RibhavBansal** [comment]
claim

**Comment by IEC2021103Abhinav** [comment]
Claim
