### ISSUE TITLE
Design the LoginActivity for the application and implement a few transition functionalities.

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#26]
You have to design the LoginActivity for the application, It should contain the app's icon at the top, along with the name of the app "SuperQuizzer" and then it should contain Email ID and Password EditText's along with a login button and "Dont' have an account:? Sign Up" option. Sign Up should be a seperate TextView with an onclick Listener added, clicking the Sign Up TextView should transition the app to the RegisterActivity.  __Also, for now, clicking the Login Button Should take you to the MainActivity__, for testing purposes.  No need to add the "Forgot Password" option. 

Here is an example design for a LoginActivity of an application. It should look like something similar to this, you can add colorful gradients as background. Try to keep the design minimalistic.

![image](https://user-images.githubusercontent.com/97402494/208585459-f89074b4-5104-40f3-98a1-90f9993833c2.png)

**Comment by unreasonable2003** [comment]
Claim

**Comment by IEC2021103Abhinav** [comment]
Claim
