### ISSUE TITLE
Add a navigation drawer in the MainActivity along with a menu drawer icon.

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#27]
In the MainActivity of the the application, you have to implement a Navigation Drawer so that after clicking on the menu drawer icon OR swiping from left to right, a navigation drawer should be shown with the My Account, Settings and Log Out options.

It should look something like this: 

https://user-images.githubusercontent.com/97402494/208660980-9fc73edc-eeee-4089-920e-19bf1e56cec1.mp4

You can refer to the GeeksGeeks article for your reference, you can add the gradle dependencies that will be used and create a menu folder under the res folder if you want to.

Attach a .gif of using the navigation drawer in the MainActivity when submitting a PR.

**Comment by unreasonable2003** [comment]
claim

**Comment by SuhailAhmadKhan** [comment]
> claim

@unreasonable2003  You are already working under one issue in the repo, finish that task first then I can give you this issue if someone else does not claim it.

**Comment by akshatsgh** [comment]
claim

**Comment by SuhailAhmadKhan** [comment]
> claim

@akshatsgh  The issue has been assigned to you.

**Comment by IEC2021103Abhinav** [comment]
Claim

**Comment by SuhailAhmadKhan** [comment]
@akshatsgh updates?

**Comment by akshatsgh** [comment]
Will submit it before deadline
