### ISSUE TITLE
Change App Font

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#44]
## Issue Description

* Download the Montserrat Font from the Internet.
* Change the default app font to Montserrat.
* Attach the screenshot after running the Application with the added font.

**Comment by anshgeez31** [comment]
claim

**Comment by akshatsgh** [comment]
claim

**Comment by RibhavBansal** [comment]
claim

**Comment by SuhailAhmadKhan** [comment]
@anshgeez31  you have been assigned this issue.
