### ISSUE TITLE
Write logic for validateLoginDetails() Function in LoginActivity

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#50]
You have to implement a few checks in the LoginActivity of the application, if the Email ID and Password EditText's are blank, it should display a message saying Email ID cannot be blank and Password cannot be blank respectively, also, then the login button is clicked, if the Email ID and password edittext's are not blank then only it should go to The MainActivity, otherwise clicking the Login Button should display the error Toast and should NOT transition to the MainActivity of the application.

In case you have any doubts, feel free to ask in the Discord channel of SuperQuizzer.

**Comment by unreasonable2003** [comment]
claim

**Comment by anshgeez31** [comment]
claim

**Comment by akshatsgh** [comment]
claim

**Comment by IEC2021103Abhinav** [comment]
Claim

**Comment by SuhailAhmadKhan** [comment]
@unreasonable2003  you have been assigned this issue, you have 48 hours to work on it.

**Comment by SuhailAhmadKhan** [comment]
This issue is up for claims again!

**Comment by anshgeez31** [comment]
claim

**Comment by anshgeez31** [comment]
@SuhailAhmadKhan my PR has been merged for collaborative web and I have also told Manas to close that issue. So please assign me this issue

**Comment by SuhailAhmadKhan** [comment]
@anshgeez31  assigned.

**Comment by IEC2021103Abhinav** [comment]
claim
