### ISSUE TITLE
Fix one of the transitions and remove the app and status bar from the top of RegisterActivity.

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#52]
When the application is opened, the RegisterActivity is displayed after the SplashScreen, you have to make it so that after opening the application and SplashScreen being displayed for 3s, LoginActivity should be displayed instead of the RegisterActivity. 

Also, there are still app and status bar present on the top of the RegisterActivity, you have to remove them so it looks similar to the login Activity

LoginActivity:
![Screenshot_2022-12-23-19-04-20-269_com example superquizzer](https://user-images.githubusercontent.com/97402494/209345621-507ed771-47f6-4d49-8605-debcdaf8c7df.jpg)

RegisterActivity
![Screenshot_2022-12-23-19-04-15-088_com example superquizzer](https://user-images.githubusercontent.com/97402494/209345689-0be9cd00-c2a8-40f3-b4be-82013f44bf3b.jpg)

Attach a .gif of opening the application, LoginActivity being displayed after SplashScreen, going to the RegisterActivity and showing the changes while submitting a PR.

**Comment by IEC2021103Abhinav** [comment]
Claim

**Comment by anshgeez31** [comment]
claim

**Comment by SuhailAhmadKhan** [comment]
@IEC2021103Abhinav  you have been assigned this issue.
