### ISSUE TITLE
Implement Authentication using Firebase in the RegisterActivity

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#54]
This is the first issue that requires **Firebase Implementation** in our application. Provide your email address  by commenting while claiming the issue or after claiming the issue, and I will add you as a member to the Project's Firebase Portal
You can access it then here: https://console.firebase.google.com/u/3/project/superquizzer-8cb6c/overview 

In the registerUser function inside the if (isAllEditTextCheck) condition, instead of showing Registation successful toast add firebase code to  register the user for the application in the firebase portal. After the user clicks register button, if(isAllEditTextCheck) -> it should register the User inside the Firebase Portal and the user's email ID and password  should be displayed in the Firebase Portal like this
![image](https://user-images.githubusercontent.com/97402494/209413932-f26219ed-d4b4-4f94-8824-b68831b18d6f.png)

Attach a .gif of filling all the text fields in the RegisterActivity, and clicking register button, after that show the firebase console and the email and password that you entered must be present there in the console.

You can watch this video for your reference: https://www.youtube.com/watch?v=BxlFuMqXiCw

In case you have any further doubts, feel free to ask in discord channel of SuperQuizzer.

**Comment by akshatsgh** [comment]
Claim

**Comment by anshgeez31** [comment]
Claim kothariansh31@gmail.com

**Comment by IEC2021103Abhinav** [comment]
Claim

**Comment by SuhailAhmadKhan** [comment]
> kothariansh31@gmail.com

you already have 3 active issues, I cannot assign this issue to you right now.

**Comment by SuhailAhmadKhan** [comment]
> Claim

you already have one issue active under the current repo, I also cannot assign this issue to you right now,

**Comment by IEC2021103Abhinav** [comment]
claim
