### ISSUE TITLE
Create a layout file for the RegisterActivity.

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#6]
The RegisterActivity will contain all the code related to the registration process for the application. You have to design the basic layout for the RegisterActivity using XML's ConstraintLayout. It should contain the First Name, Last Name, Email Address, Password, Confirm Password EditText's and CheckBox for Terms And Conditions.

Here is an example of a RegisterActivity Layout for your reference, the color scheme and other variables should be custom but it should look something similar to this: 
---
![image](https://user-images.githubusercontent.com/97402494/208246437-357ca9d2-866d-4542-ab13-d343295696c2.png)
---
You will have to write the code here: [activity_register.xml](https://github.com/opencodeiiita/SuperQuizzer/blob/main/app/src/main/res/layout/activity_register.xml)
---
Guidelines
- Only ConstraintLayout should be used
- No hardcoded text will be allowed. Make strings in the [strings.xml](https://github.com/opencodeiiita/SuperQuizzer/blob/main/app/src/main/res/values/strings.xml) file
- Custom colors (if used) should be added in [colors.xml](https://github.com/opencodeiiita/SuperQuizzer/blob/main/app/src/main/res/values/colors.xml)
---
Feel free to ask doubts in the discord server's SuperQuizzer Channel 
---

**Comment by IEC2021103Abhinav** [comment]
claim

**Comment by unreasonable2003** [comment]
claim

**Comment by RibhavBansal** [comment]
claim

**Comment by RibhavBansal** [comment]
claim
