### ISSUE TITLE
Create a new Empty Activity named as ForgotPasswordActivity and design it's layout in XML.

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#62]
You have to create a new empty activity named as ForgotPasswordActivity and design it's layout in XML. The design should look as close to this as possible.
![image](https://user-images.githubusercontent.com/97402494/209453161-07945cac-609f-4caf-9e86-6988c4bcbf6f.png)
Instead of Login, the button should say Submit, also for the waves at the bottom, you can use this [website](https://getwaves.io/)

Attach a screenshot of the layout while submitting a PR.

**Comment by anshgeez31** [comment]
Claim

**Comment by SuhailAhmadKhan** [comment]
> Claim

You already have an issue active under this repo.

**Comment by IEC2021103Abhinav** [comment]
Claim

**Comment by RibhavBansal** [comment]
claim
