### ISSUE TITLE
Implement Authentication using Firebase in the LoginActivity.

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#66]
This  issue  requires **Firebase Implementation** in our application. Provide your email address  by commenting while claiming the issue or after claiming the issue, and I will add you as a member to the Project's Firebase Portal
You can access it then here: https://console.firebase.google.com/u/3/project/superquizzer-8cb6c/overview 

You have to make sure that if an email and password that is already registered using the RegisterActivity and stored in Firebase is entered in the LoginActivity, then only login should be successful and it should go to the main activity saying Login Successful, otherwise it should show an error and not go to the MainAcitvity. 

Attach a .gif showing both a success and a failure case.

You can refer to this article for your Reference, check the LoginAcitivty part. https://www.geeksforgeeks.org/login-and-registration-in-android-using-firebase-in-kotlin/

In case you have any further doubts, feel free to ask in discord channel of SuperQuizzer.

**Comment by akshatsgh** [comment]
claim

**Comment by anshgeez31** [comment]
Claim

**Comment by IEC2021103Abhinav** [comment]
Claim

**Comment by SuhailAhmadKhan** [comment]
@akshatsgh updates?

**Comment by akshatsgh** [comment]
done
