### ISSUE TITLE
Make a few changes in the ForgotPasswordActivity of the application.

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#67]
You have to do the following things: 

1. Add a check to the email editText, if email address is blank or not valid format, it should display a message saying so. If valid email Address is entered, clicking on submit should take you to the LoginActivity along with success toast.
2. Implement a back button on the top left of the forgotpassword Activity. clicking on it should take you to the LoginActivity.
![image](https://user-images.githubusercontent.com/97402494/209616427-83820d4d-aacf-4c77-a91c-5d225cb05559.png)

**Comment by IEC2021103Abhinav** [comment]
Claim
