### ISSUE TITLE
Make SplashActivity the first screen and create transition with delay.

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#7]
You have to ensure that the [SplashActivity](https://github.com/opencodeiiita/SuperQuizzer/blob/main/app/src/main/java/com/example/superquizzer/SplashActivity.kt) is the first screen that is displayed when the application is opened by the user. Also add a transition from [SplashActivity](https://github.com/opencodeiiita/SuperQuizzer/blob/main/app/src/main/java/com/example/superquizzer/SplashActivity.kt) to [RegisterActivity](https://github.com/opencodeiiita/SuperQuizzer/blob/main/app/src/main/java/com/example/superquizzer/RegisterActivity.kt) with a delay of 3 seconds. i.e , once the app is opened, The SplashActivity should be displayed for 3 seconds and then it should switch to the RegisterActivity. 

Also remove the title bar from the top of SplashActivity. 
![image](https://user-images.githubusercontent.com/97402494/208269833-fb1e2959-2ce2-4f42-b478-c86153f81fb3.png)

**Comment by anshgeez31** [comment]
claim

**Comment by IEC2021103Abhinav** [comment]
Claim

**Comment by unreasonable2003** [comment]
Claim

**Comment by RibhavBansal** [comment]
claim
