### ISSUE TITLE
Change the layout of the RegisterActivity in order to match with the rest of the application.

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#70]
Currently the RegisterActivity has different colors and style as compared to the rest of the application. You have to make it so that the RegisterActivity looks similar to the Login and Forgot Password Activities. The background color should be white, the EditText's should look similar to the one's in the LoginActivity, use icons for FirstName, LastName and ConfirmPassword  as well at the side. Make sure the I agree to the Terms and Conditions is centered properly. Change the color of the button accordingly as well and make sure it has rounded edges. . Also, shift the back button at the top left of the screen to a bit more left and implement it's functioning. Clicking on it should take you back to the LoginActivity. 

__THE ID'S OF EVERY ELEMENT SHOULD REMAIN THE EXACT SAME. DO NOT CHANGE THEM.__

Attach a screenshot of the new RegisterActivity layout when submitting a PR.

**Comment by IEC2021103Abhinav** [comment]
Claim
