### ISSUE TITLE
Create a new layout file named dialog_progess.xml

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#71]
You have to create a new layout file named dialog_progress.xml . It should simply display a progress bar along with a TextView saying "Please Wait..." The background should be black and the Please Wait Text should be white,

Here is an image for reference, note that it does not match with the color scheme I mentioned.
![image](https://user-images.githubusercontent.com/97402494/209722664-b65e83e5-2f32-4346-8f43-afc7bb539ddc.png)

attach a screenshot of the layout while submitting a PR.

**Comment by IEC2021103Abhinav** [comment]
Claim

**Comment by akshatsgh** [comment]
Claim

**Comment by SuhailAhmadKhan** [comment]
@IEC2021103Abhinav  You already have an issue claimed under this repo, right now I cannot assign it to you.

**Comment by SuhailAhmadKhan** [comment]
@akshatsgh  assigned

**Comment by SuhailAhmadKhan** [comment]
@akshatsgh  updates?

**Comment by IEC2021103Abhinav** [comment]
Claim

**Comment by SuhailAhmadKhan** [comment]
@IEC2021103Abhinav  you already have an active issue in this repo

**Comment by zitsav** [comment]
claim

**Comment by SuhailAhmadKhan** [comment]
@zitsav  assigned
