### ISSUE TITLE
Create a new data class named Question.kt

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#73]
You have to create a new data class named Question.kt and add the following val's inside it ->

 id -> type int
question -> type string
optionOne -> type string 
optionTwo -> type string
optionThree -> type string
optionFour -> type string
correctOption -> type int

This data class will be used later while setting up the questions for our quizzes.

**Comment by IEC2021103Abhinav** [comment]
Claim
