### ISSUE TITLE
Send a password reset email using Firebase in the ForgotPasswordActivity

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#76]
This  issue  requires **Firebase Implementation** in our application. Provide your email address  by commenting while claiming the issue or after claiming the issue, and I will add you as a member to the Project's Firebase Portal
You can access it then here: https://console.firebase.google.com/u/3/project/superquizzer-8cb6c/overview 

You have to implement Firebase Authentication in the ForgotPasswordActivity, if a valid email address is entered that is already registered, on clicking the submit button, the user should get an email to reset their password. Also add check for failure case.

Attach a screenshot of an email that you get on submitting your email in the ForgotPasswordActivity.

You can refer to the Firebase Docs for your reference here: https://firebase.google.com/docs/auth/android/manage-users#send_a_password_reset_email

**Comment by anshgeez31** [comment]
Claim

**Comment by anshgeez31** [comment]
kothariansh31@gmail.com

**Comment by IEC2021103Abhinav** [comment]
Claim

**Comment by SuhailAhmadKhan** [comment]
@anshgeez31  updates?

**Comment by IEC2021103Abhinav** [comment]
Claim
