### ISSUE TITLE
Implement the Logout feature in the navigation drawer.

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#78]
This  issue  requires **Firebase Implementation** in our application. Provide your email address  by commenting while claiming the issue or after claiming the issue, and I will add you as a member to the Project's Firebase Portal
You can access it then here: https://console.firebase.google.com/u/3/project/superquizzer-8cb6c/overview 

You have to implement the Sign Out Feature in the navigation drawer of the MainActivity, on clicking the Logout option a new pop up should be generated. You have to make a seperate layout file for this popup and make sure it matches the color scheme and theme of the application overall. (use white,black,purple etc) . A popup should appear at the centre of the screen and it should ask if the user is sure they want to log out or not, clicking on the yes option should sign out the user from the application, and clicking the no option should take them back to the screen. (the popup should hide). Implement firebase authentication sign out feature for the sign out part.

![image](https://user-images.githubusercontent.com/97402494/210018133-0ad6c080-09a3-445c-8470-9ce3de90bf73.png)

**Comment by IEC2021103Abhinav** [comment]
Claim
