### ISSUE TITLE
Create layout file named quiz_activity.xml for all the different quiz activities. 

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#84]
This will be the screen of the application whenever a quiz is active. For the content of the question and options, just add placeholder text inside the TextViews for now. 

Here is an example of the layout file of a Quiz Activity: 

![image](https://user-images.githubusercontent.com/97402494/210117210-c0df6b2d-d59c-4a4b-bddb-015ec9e23167.png)
This image is only for your reference, you do not have to replicate it. Something similar will suffice. 

Make sure to add Correct and Wrong TextFields, a submit button and a next button. The question number out of the total number of questions (10) should also be displayed somewhere. You can also add a ProgressBar if you want to.

Add screenshots of the layout file while submitting a PR.

**Comment by sushantk1274** [comment]
CLAIM

**Comment by sushantk1274** [comment]
claim

**Comment by SuhailAhmadKhan** [comment]
@sushantk1274  updates?

**Comment by Koshal7** [comment]
claim

**Comment by Koshal7** [comment]
claim
