### ISSUE TITLE
Create getQuestions() function in a new object named ScienceQuestions.kt

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#89]
Create a new object named ScienceQuestions which contains a function of type ArrayList<Question> named getScienceQuestions() .

It should contain an ArrayList of Questions from 1 to 10 named question1, question2,question3 etc. You have to define these questions according to the Questions data class, find 10 Science  MCQ Questions from the internet and set them accordingly, id first, then question, then all it's options, then correct option number and then add these questions to the ArrayList. Return the ArrayList at the end of the function.

**Comment by akshatsgh** [comment]
claim

**Comment by IEC2021103Abhinav** [comment]
Claim

**Comment by sushantk1274** [comment]
claim

**Comment by SuhailAhmadKhan** [comment]
@akshatsgh  assigned
