### ISSUE TITLE
Add Questions in ScienceQuestions Activity

### ISSUE THREAD

**Issue by SuhailAhmadKhan** [opencodeiiita/SuperQuizzer#95]
create a new activity named science questions, clicking on the science option in the MainActivity should take you to this activity, 

quiz questions layout is already given, get all the Science Questions that are given in the Questions.kt and display them one by one in the ScienceQuestions Activity, also maintain a score. If the answer submitted is correct, score should increase by one. Clicking next should just go to the next question. Also, keep on increasing the ProgressBar after each question is answered. After 10th question is answered and submitted/next is pressed. It should take you to a new Empty Acitivty named ResultActivity.

If you have any further doubts, you can ask in SuperQuizzer Discord channel.

**Comment by zitsav** [comment]
claim 😳

**Comment by IEC2021103Abhinav** [comment]
claim
